#!/bin/bash
data=$(cat /usr/bin/smend/data/auth.lib/1.txt) #read the results from the authlib dir
case $data in
TRUE);;
FALSE) echo Cannot continue; exit;;
esac
tput clear
tput cup 0 0
tput cup 10 20; echo "SMEND File patch menu"
tput cup 11 20; echo "1) Edit a file"
tput cup 12 20; echo "2) Delete a file"
tput cup 13 20; echo "3) exit"
tput cup 10 41; read menu
case $menu in
1) smend -ed;;
2) smend -rc;;
3) exit;;
esac
